services:
  database:
    image: postgres:18.1-alpine3.23
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "$BIND_DB_PORT:5432"
    volumes:
      - docker/pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:debug
    ports:
      - "$BIND_SERVER_PORT:3000"
    depends_on:
      - database
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    extra_hosts:
      - coreserver:host-gateway
